### PR TITLE
aligned the button and turnstile with the 33% width box and removed t…

### LINKED ISSUE #83: Fix positioning of Turnstile
Image

Likely just need to make the containers each 33% of the total width of the parent.

### PR DESCRIPTION
**Pull request by daylieveryday**
Closes #83

### CODE REVIEW

**Review by ashlyndevries — CHANGES_REQUESTED** [review]
Turnstile needs to be aligned on the `idcheckin` and `namecheckin` pages as well. 

Best practice: shorten your PR titles be only as many words as sufficient to explain your task, eg. `Re-aligned Turnstile title with top row buttons`.

Great job creating a `fix/` branch rather than a `feature/`, however! Easy best practice to forget when features branches are so common.

**Review by SpBills — APPROVED** [review]
Overall, very good job.

I do not think that we need any of the display="flex" or flexDirection attributes on any of these though.

**Review by ashlyndevries — APPROVED** [review]
LGTM.

**Comment by ashlyndevries** [comment]
By removing the `display="flex"` and `flexDirection="column"`, though Turnstile remains centered, the buttons do not:

image

**Pull request merged**
